# Generated by Django 5.2.15 on 2026-07-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuFormatSeries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(help_text='Module code/name, e.g. inventory.purchase_requisition, inventory.item', max_length=150)),
                ('name', models.CharField(help_text='Human label, e.g. Item SKU', max_length=120)),
                ('prefix', models.CharField(blank=True, default='', help_text='Prefix like ITM', max_length=30)),
                ('suffix', models.CharField(blank=True, default='', help_text='Optional suffix', max_length=30)),
                ('use_series', models.BooleanField(default=True, help_text='Use auto-increment numeric series: SKU_CODE-0001')),
                ('counter', models.PositiveIntegerField(default=0, help_text='Next number to use')),
                ('counter_pad', models.PositiveIntegerField(default=4, help_text='Zero padding width, 4 -> 0001')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allow multiple SKU formats for this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_formats', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_formats_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_sku_format_series',
            },
        ),
        migrations.CreateModel(
            name='SkuFormatSelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=150, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_format_selection', to=settings.AUTH_USER_MODEL)),
                ('default_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_module', to='sku_settings.skuformatseries')),
            ],
            options={
                'db_table': 'settings_sku_format_selection',
            },
        ),
        migrations.AddIndex(
            model_name='skuformatseries',
            index=models.Index(fields=['module', 'is_active'], name='settings_sk_module_79f881_idx'),
        ),
        migrations.AddIndex(
            model_name='skuformatseries',
            index=models.Index(fields=['module', 'name', 'is_active'], name='settings_sk_module_206ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='skuformatselection',
            index=models.Index(fields=['module'], name='settings_sk_module_d0217f_idx'),
        ),
    ]
