# Generated by Django 5.2.15 on 2026-07-05 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='source_warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH_A', 'Branch A'), ('BRANCH_B', 'Branch B')], default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='target_warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH_A', 'Branch A'), ('BRANCH_B', 'Branch B')], default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH_A', 'Branch A'), ('BRANCH_B', 'Branch B')], default='MAIN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['warehouse', 'created_at'], name='inventory_s_warehou_80e7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_type'], name='inventory_s_move_ty_0fa310_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['source_warehouse', 'target_warehouse'], name='inventory_s_source__abdeab_idx'),
        ),
    ]
