# Generated by Django 5.2.15 on 2026-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmove_source_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='default_warehouse',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main Warehouse'), ('BRANCH_A', 'Branch A'), ('BRANCH_B', 'Branch B')], max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='is_fixed_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_inventory_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_purchase_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sales_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='item_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='profit_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_gl_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_gl_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='uom_conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='withholding_tax',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
