# Generated by Django 5.2.15 on 2026-07-05 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_cost_center_item_default_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='default_warehouse',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='source_warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='target_warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='warehouse',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], default='MAIN', max_length=20),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('warehouse_type', models.CharField(choices=[('MAIN', 'Main Warehouse'), ('BRANCH', 'Branch'), ('SUB', 'Sub Warehouse'), ('VIRTUAL', 'Virtual')], default='MAIN', max_length=20)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('profit_center', models.CharField(blank=True, max_length=100)),
                ('gl_account', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('HOLD', 'Hold')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_warehouses', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'), models.Index(fields=['status'], name='inventory_w_status_3a8843_idx'), models.Index(fields=['branch'], name='inventory_w_branch_411e3e_idx')],
            },
        ),
    ]
