# Generated by Django 5.2.15 on 2026-07-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('recon_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recon_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('payment_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RECEIPT', 'Receipt'), ('ADVANCE', 'Employee Advance')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('payment_date', models.DateField()),
                ('paid_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='journalentryline',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounting__code_04da0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__status_41d9ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__referen_4bf694_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reference_type',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliationline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='bankreconciliationline',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_entries', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationline',
            index=models.Index(fields=['reconciliation', 'journal_entry'], name='accounting__reconci_226066_idx'),
        ),
    ]
