# Generated by Django 5.2.15 on 2026-07-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_currency_is_base'),
        ('governance', '0003_sync_companyconfig_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_accounts', to='governance.companyconfig'),
        ),
        migrations.AddField(
            model_name='account',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='report_type',
            field=models.CharField(blank=True, choices=[('Balance Sheet', 'Balance Sheet'), ('Profit and Loss', 'Profit and Loss')], max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='root_type',
            field=models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
