# Generated by Django 5.2.15 on 2026-07-05 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('company_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('tax_registration_number', models.CharField(blank=True, default='', max_length=128)),
                ('default_valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('AVCO', 'AVCO'), ('STANDARD', 'STANDARD')], default='AVCO', max_length=20)),
                ('unrealized_profit_loss_account', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('currency_symbol', models.CharField(blank=True, default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('cycle_count_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COUNTING', 'Counting'), ('RECONCILED', 'Reconciled')], default='DRAFT', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_timezone', models.CharField(default='UTC', max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='governance.companyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=128)),
                ('record_id', models.CharField(max_length=128)),
                ('action_type', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=16)),
                ('old_values_json', models.JSONField(blank=True, null=True)),
                ('new_values_json', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='governance.companyconfig')),
            ],
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_base_currencies', to='governance.currency'),
        ),
        migrations.CreateModel(
            name='CycleCountItem',
            fields=[
                ('count_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('variance_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('adjustment_journal_entry_id', models.CharField(blank=True, default='', max_length=128)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='governance.cyclecount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_items', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='DecimalConfig',
            fields=[
                ('config_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('currency_decimals', models.PositiveSmallIntegerField(default=2)),
                ('quantity_decimals', models.PositiveSmallIntegerField(default=4)),
                ('price_decimals', models.PositiveSmallIntegerField(default=4)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decimal_configs', to='governance.companyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('period_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_globally_locked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='governance.companyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GLDefaultAccount',
            fields=[
                ('config_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ar_default_account', models.CharField(blank=True, default='', max_length=64)),
                ('ap_default_account', models.CharField(blank=True, default='', max_length=64)),
                ('revenue_default_account', models.CharField(blank=True, default='', max_length=64)),
                ('cogs_default_account', models.CharField(blank=True, default='', max_length=64)),
                ('inventory_asset_account', models.CharField(blank=True, default='', max_length=64)),
                ('tax_payable_account', models.CharField(blank=True, default='', max_length=64)),
                ('tax_receivable_account', models.CharField(blank=True, default='', max_length=64)),
                ('fx_gain_loss_account', models.CharField(blank=True, default='', max_length=64)),
                ('inventory_adjustment_account', models.CharField(blank=True, default='', max_length=64)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gl_defaults', to='governance.companyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('layer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_receipt_id', models.CharField(blank=True, default='', max_length=128)),
                ('layer_date', models.DateTimeField()),
                ('received_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('remaining_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('is_fully_consumed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='governance.companyconfig')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('AVCO', 'AVCO'), ('STANDARD', 'STANDARD'), ('INHERIT', 'INHERIT')], default='INHERIT', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='governance.companyconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('is_virtual', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='governance.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryJournal',
            fields=[
                ('inv_journal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_document_type', models.CharField(max_length=64)),
                ('source_document_id', models.CharField(blank=True, default='', max_length=128)),
                ('quantity_delta', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_valuation_delta', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='governance.inventorycostlayer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_journals', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_journals', to='governance.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='governance.warehouse'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='governance.warehouse'),
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('rate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_rates', to='governance.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_rates', to='governance.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
        migrations.CreateModel(
            name='ModulePeriodLock',
            fields=[
                ('lock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_locks', to='governance.fiscalperiod')),
            ],
            options={
                'unique_together': {('period', 'module_name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='governance.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='governance.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserCompanyAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='governance.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='governance.companyconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity_reserved', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('quantity_available', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('average_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='governance.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
