# Generated by Django 5.2.15 on 2026-07-05 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchasing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchasing__supplie_3527d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchasing__created_1e1e86_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='purchasing__code_88ef59_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierinvoice',
            name='purchasing__supplie_7cb8c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierinvoice',
            name='purchasing__outstan_dd8505_idx',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='supplierinvoice',
            name='tax',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddIndex(
            model_name='grnitem',
            index=models.Index(fields=['grn', 'item'], name='purchasing__grn_id_d08a73_idx'),
        ),
    ]
